### ISSUE TITLE
Spotkanie marcowe (20.03.2015) - Feedback

### ISSUE THREAD

**Issue by afronski** [nodeschool/silesia#10]
Jeśli macie jakieś uwagi, pytania, wątpliwości, podzielić się uwagami które dotyczą pierwszego spotkania, możecie śmiało dodać komentarz w tym wątku. Dzięki temu przyszłe edycje przeprowadzimy sprawniej i efektywniej.

Jeśli ktoś chciałby, zgłosić feedback bardziej anonimowo - możecie śmiało napisać na adres: nodeschoolpl@rspective.com

**Comment by MariuszGeo** [comment]
witam, 
gdzie się jutro widzimy i o której? będą bilety jak ostatnio i muszę się gdzieś specjalnie zapisywać czy po prostu się jutro zjawić z lapkiem pod wskazany adres?

**Comment by afronski** [comment]
Cześć @MariuszGeo - wydarzenie i szczegóły są tutaj: http://www.meetup.com/NodeSchool-Silesia/events/221083677/ - tym razem nie ma biletów, daj tylko _RSVP_, że będziesz. :wink:

**Comment by MariuszGeo** [comment]
dzięki i do jutra :)

**Comment by frakti** [comment]
Sorry za spóźniony feedback.
Pewno po kilku spotkaniach wyklarują się ciekawe pomysły usprawniające warsztaty.
Po pierwszym mam odczucie, że brakuje nam większej współpracy między uczestnikami. Wiąże się to z drugim spostrzeżeniem. Momentami miałem wrażenie, że wiedza nie propaguje się na resztę, zamyka się tylko w gronie naszych sąsiadów, a czasem zostawiamy je dla siebie. 

To co bym proponował, to spisywać gdzieś  na whiteboardzie te ciekawsze problemy/pytania/wskazówki i np. co 30 min, robić sobie krótką przerwę w czacie której omawiamy owe tematy. 
Generalnie dzielmy się małymi porcjami lessons learned ;-)

Co o tym myślicie?

**Comment by afronski** [comment]
Dobry pomysł @frakti - proponuję, aby wdrożyć już jutro pomysł z przerwami i wymianą wiedzy w grupie bardziej doświadczonych osób - dodaj proszę ten feedback tutaj: #11.

**Comment by MariuszGeo** [comment]
co mogę dodać :) część osób ostanim razem nie była przystosowana do środowiska na którym pracujecie :) ja sam nie jestem głupi (przynajmniej tak mi się wydawało :)) z tematów informatycznych ale wdrażanie typu "kiliknij to" w linuxa (na którym ostatni raz sie bawiłem 8 lat temu) może nie jest najlepszą techniką do zapoznywania z nowymi, pokazywanymi przez Was treściami, bo można się było poczuć (choć cierpliwość i zrozumienie osób pomagających była wprost nieograniczona, mówię jedynie o osobistym odczuciu, a w zasadzie osobistym poczuciu porażki :D ) jak na zajęciach przedwstępnych z obsługi komputera na Uniwersytecie III Wieku :)
zrozumcie mnie dobrze :) nie chodzi o to, żeby uczyć ludzi linuxa i XYZ rzeczy, ale wystarczy tych, które wykorzystujemy na Waszych zajęciach :) może warto się umówić z tymi naprawdę początkującymi (których teraz może de facto być więcej) nieco wcześniej na instalację i konfigurację środowiska, bo tylko koło mnie 2 osoby były z Windowsem (zainstalować im maszynę wirtualną, Linuxa, Sublime i w 10 min wytłumaczyć o co chodzi na początku spotkania w sensie jak sie poruszać). Nie zaczynać od learnyounode tylko od klasycznego modułu JS (osoby, które cośtam kojarzą w innych językach się rozbudzą), przerobić ten podstawowy kurs przedwstępny i ludzie wtedy sami na node.js wskoczą . Myślę, że sporo ludzi którzy przychodzących na zajęcia ma naprawdę jakieś pojęcie, tylko wystarczy ich sprytnie ukierunkować na Wasz system pracy i ogarniania tematu :)

**Comment by afronski** [comment]
@MariuszGeo Mamy podobne obserwacje po ostatnim spotkaniu - przede wszystkim z Naszej strony zabrakło warsztatu _javascripting_, który tym razem będzie. Spróbujemy też inaczej podejść do tematu instalacji i prezentacji pierwszego zadania - więcej szczegółów tutaj: #11 - daj znać co o tym myślisz. :smile: Dzięki za feedback!

**Comment by afronski** [comment]
Nasunęła mi się jedna myśl (@tpindel miał podobną) po dzisiejszym spotkaniu: 2.5h intensywnego myślenia to bardzo długo - może warto wyznaczyć _obowiązkowy_ czas na przerwy i networking, żeby dać trochę odpocząć głowie po ciężkim dniu pracy i np. 1h intensywnej pracy nad warsztatem.

**Comment by derberg** [comment]
Może mała podpowiedz do tematu konfiguracji środowiska, szczególnie, że wczoraj kilka osób znowu miało problem z windowsem. Kiedyś, na jednej konferencji, na warsztacie gdzie próbowaliśmy kilka topowych baze NoSQL widziałem eleganckie usprawnienie. Organizator przygotowal image linucha z doinstalowanymi wszystkimi bazami, z pelna konfiguracja i materialami ćwiczebnymi na pulpicie. Wystarczylo zainstalowac Virtual Boxa i warsztaty bez problemu zaczely sie w 5 minut.

**Comment by afronski** [comment]
@derberg Dzięki za feedback. VMka to dobry pomysł, ale z własnego doświadczenia wiem, że nie jest to tak proste i bezproblemowe do skonfigurowania, zwłaszcza jeśli chodzi o dostęp do sieci, dwukierunkowe współdzielenie plików i różne wersje zainstalowanego _VirtualBox_/_VMware_/etc. To tego b. często dochodzi bariera dot. pracy przez SSH. 

Mieliśmy pomysł, który opierał się o maszyny wirtualne i narzędzie _vagrant_, natomiast musimy go jeszcze bardziej dopracować, żeby setup był faktycznie typowym _click-and-play_.

**Comment by afronski** [comment]
Dodałem zadania zw. z usprawnieniami na następne spotkanie #12, #13 oraz #14.

Dziękujemy za feedback i zachęcamy do zakładania nowych _issue_ jeśli macie pomysł na usprawnienia lub jakikolwiek feedback dot. spotkań! :wink:
