### ISSUE TITLE
Plan i organizacja spotkania

### ISSUE THREAD

**Issue by afronski** [nodeschool/silesia#11]
1. Dzielimy uczestników na dwie grupy:
   - _Greenhorns_, którzy do przychodzą pierwszy raz na spotkanie (niezależnie od warsztatu - _learnyounode_ czy _javascripting_).
   - _Power Users_, którzy pojawiają się kolejny raz na spotkaniu, mają doświadczenie z _Node.js_ (dowolny, inny warsztat).
2. Grupę pierwszą dzielimy na uczestników _javascripting_ lub _learnyounode_, do każdej z podgrup przyporządkowujemy dwóch opiekunów.
   - Każdy z opiekunów na własnym komputerze zaprezentuje krótką prezentację, zainstaluje Node.js i pokaże jak zrobić pierwsze zadanie z danego warsztatu oraz jak posługiwać się _workshopperem_. 
   - Wprowadzenie nie powinno trwać dłużej niż _5-10 minut_.
3. Drugą grupę dzielimy na podgrupy związane z konkretnymi warsztatami.
   - Do każdej podgrupy przyporządkowujemy opiekuna, który zajmie się wstępem teoretycznym.
   - Wprowadzenie nie powinno trwać dłużej niż _15 minut_.
4. Wprowadzenia odbywają się równolegle, po ich zakończeniu uczestnicy przechodzą do wykonywania zadań, a opiekunowie krążą i pomagają przezwyciężyć problemy.

**Comment by tpindel** [comment]
@afronski Wygląda spoko. Może warto spisac i utrzymaywać te reguły gdzies na stronce nodeschool. Dzieki temu wszyscy beda znali zasady juz przed przystapieniem do warsztatu.

**Comment by afronski** [comment]
@tpindel Dobry pomysł - możemy skorzystać z wiki w tym repozytorium albo rozbudować stronę. Musimy tylko poczekać aż te reguły się _wyklarują_ i sprawdzą w praktyce.

**Comment by pawelrychlik** [comment]
:+1: zobaczmy jak to wyjdzie w praktyce

**Comment by frakti** [comment]
Zgodnie z dyskusją w #10, proponuję dodać podpunkt do _3_:

> Grupy tematyczne w trakcie rozwiązywania zadań spisują uwagi/spostrzeżenia/lessons learned i co 30 min robimy max 5 min przerwę celem omówienia spisanych tematów

W praniu wyjdzie czy te tematy omawiamy w ramach podgrup, czy wśród wszystkich _Power Users_.

**Comment by afronski** [comment]
Okej - przenosimy to do [pliku](https://github.com/nodeschool/silesia/blob/master/meetings/MEETING-PLAN.md).

Zachęcam do review i otwarcia nowego _issue_ jeśli coś jest nie tak, lub macie pomysły usprawnienia. :wink:
