### ISSUE TITLE
International Day (23.05)

### ISSUE THREAD

**Issue by afronski** [nodeschool/silesia#17]
## Opis

Zbiór zadań, oraz tego co powinno być w planie i co powinniśmy mieć przygotowane do _nodeschool/international-day_.
## Merytoryka
- [x] Pomysły (mogą odbywać się równolegle):
  - [x] Standardowe warsztaty.
  - [x] _Future track_ (prezentacje):
    - [x] _ES 6: let, class, new syntax and new types_ - @kubavanzen 
    - [x] _Web Components and Polymer_ - @awilczek 
    - [x] _Node.js / JS Debugging Tools_ - @frakti
    - [x] _AngularJS 2.0_ - @bandraszyk 
  - [x] _Hakaton_
    - Pomysł: _strona do obsługi NodeSchool - zapisy, prezentacje, automatyczne dodawanie ludzi do githuba, integracja z twitterem - wszystko zdeployowane na Heroku_.
  - [x] Dalsze przygotowanie _workshoppera_ - `rspective/websockito`.
## Plan dnia
- [x] Przygotować plan godzinowy spotkania.
- [x] Zaplanować spotkanie na _[Google Hangout](https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md#hangout)_ z innymi oddziałami.
## Organizacja
- [x] Catering
- [x] [Naklejki](https://github.com/nodeschool/international-day/tree/2015/Stickers)
- [x] [Minifilm](https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md#minifilm)
## Zapisy oraz _Social Media_
- [x] Zapisy na wydarzenie (http://meetup.com).
- [x] Ogłoszenia na _Twitterze_, _Facebooku_.
- [x] Aktualizacja na stronach:
  - [x] http://nodeschool.io/silesia
  - [x] http://slaskit.pl
  - [x] http://nodeschool.io/events
  - [x] Rezerwacja HS Silesia.

**Comment by imvanzen** [comment]
Hej, chciałbym zgłosić chęć pomocy przy organizacji eventu.
Poniżej wymieniłem obszary, którymi mógłbym się zająć lub wesprzeć odpowiedzialną grupę:
- **Standardowe warsztaty (mentor)** - brałem udział w dwóch poprzednich edycjach oraz samodzielnie rozwiązywałem workshoppery. Moja wiedza w tym obszarze mogła by być przydatna.
- **Prezentacja, Warsztaty (ES6)** - mógłbym przygotować prezentację z nowości jakie pojawiły się w najnowszej wersji EMCA Script. Miałem już przyjemność dowiedzieć się sporo na ten temat.
- **Minifilm, Naklejki** - Pracowałem przy grafice i montażu filmów. Moglibyśmy wykorzystać moje umiejętności. Mamy co najmniej dwie kamery GoPro 4 Silver wraz ze stabilizatorami DSLR. Jest czym nagrać profesjonalny materiał.

Jakia jest Wasza opinia?
Z organizacyjnych spraw, na ile dni przewidujemy event ?

**Comment by tpindel** [comment]
@kubavanzen Podoba mi się pomysł z filmem. Poza "Welcome" video dla nodeschool moglibyśmy złożyć dłuższą wersję promującą nodeschool.

**Comment by imvanzen** [comment]
@tpindel Po głowie mi chodzi krótki materiał promo przedstawiający najważniejsze elementy każdego spotkania. Do rozwinięcia tematu i nie spamowania w tym wątku proponuję otwarcie nowego Issue

**Comment by afronski** [comment]
> Z organizacyjnych spraw, na ile dni przewidujemy event ?

@kubavanzen Cały jeden dzień - sobota, ok. 8h razem z przerwami.

**Comment by afronski** [comment]
> Do rozwinięcia tematu i nie spamowania w tym wątku proponuję otwarcie nowego Issue.

@kubavanzen _Good point_, rozbijmy tego wielkoluda na mniejsze notki.

**Comment by afronski** [comment]
FTR: http://www.meetup.com/NodeSchool-Silesia/events/222231203/

**Comment by grabbou** [comment]
Co do spotkania na Hangouts -> z racji faktu, iż jesteśmy w tym samym TZ, proponuję ogarnąć wspólnie jakiś video-link. Możemy też wymienić się naklejkami jak ktoś w głównym repo zaproponował ;)

**Comment by afronski** [comment]
@grabbou _Good point_, jesteśmy zdecydowanie za. :wink:

**Comment by awilczek** [comment]
ja przygotuję prezkę z Web Components (ale nie mam tu realnego doświadczenia jak co ;) )

**Comment by afronski** [comment]
@awilczek Super! Najważniejsze, że temat Cie ciekawi.
@kubavanzen Coś konkretnego z ES6 chciałbyś przygotować? Czy chcesz zrobić przegląd przez wszystko (IMHO tego jest b. dużo jak na jedną prezentację :wink:)?

## 

Wojciech Gawroński (afronski)

**Comment by imvanzen** [comment]
@afronski Myślałem o prezentacji najciekawszych ficzerów jakie dostarcza ES6, czyli uproszczenia składni, nowe typy zmiennych, wprowadzenie klas czy też magiczny _let_.
Chciałbym powiedzieć o ich słabych i mocnych stronach oraz sprawdzić jak wpływają na performance.

Szczerze mówiąc, jeszcze nie myślałem nad dokładną agendą. Powyższą propozycję wymyśliłem na poczekaniu :) Jeśli chcielibyście zaproponować ciekawszy temat to jestem otwarty na dyskusję.

**Comment by bandraszyk** [comment]
Mógłbym zabrać AngularJS 2.0, ale potwierdzę to jeszcze w przyszłym tygodniu.

**Comment by afronski** [comment]
@bandraszyk Super! :wink:
@kubavanzen To co wymieniłeś to dobry podzbiór na prezentację :) - Możesz pokazać to na przykładzie _io.js_. Chciałbyś się zaopiekować tymi tematami?

**Comment by imvanzen** [comment]
@afronski Zajmę się tym :) Szczegóły będę omawiał już indywidualnie.

**Comment by frakti** [comment]
@afronski ja mogę zrobić prezentację na temat narzędzi do debugowania JS/node.js. Idealna okazja do odświeżenia sobie wiedzy.

**Comment by afronski** [comment]
@frakti Super! :smile: Wpiszę wszystkich na listę.

**Comment by afronski** [comment]
@frakti @kubavanzen @bandraszyk @awilczek Dodałem tematy prezentacji w pierwszym wpisie - sprawdźcie proszę czy tytuł i tematyka się zgadza.

**Comment by afronski** [comment]
:tada:

**Comment by frakti** [comment]
@afronski, gdzie wrzucamy filmik z timelapsem? YT? 
A może zmontujemy razem z głównym dokumentem, który przygotowuje @kubavanzen?

**Comment by grabbou** [comment]
Jeśli nagraliście coś do globalnego filmu tak jak w Participating.md, to polecam śledzić https://github.com/nodeschool/international-day/issues/86
