### ISSUE TITLE
Czy nodeschool silesia jeszcze żyje?

### ISSUE THREAD

**Issue by olafgoj** [nodeschool/silesia#20]
Hej, planujecie jeszcze jakieś warsztaty? :)

**Comment by p-janik** [comment]
Hej @tehgoju. Planujemy kolejne spotkanie jeszcze w tym miesiącu. Aktualnie dogadujemy datę najbliższego spotkania.

**Comment by olafgoj** [comment]
O, to super. To dwa pytania:
1. Spotkanie będzie miało formę warsztatów?
2. Czy jest sens żebym przychodził jeśli w ogóle nie znam node.js?

**Comment by p-janik** [comment]
Tak, spotkanie będzie miało formę warsztatów. 

Oczywiście, że jest sens zjawić się, jeśli nie zna się node.js. Poziom warsztatów jest indywidualny dla każdego uczestnika. 

W każdym spotkaniu uczestniczy kilka osób, które są w stanie podzielić się swoją wiedzą w temacie i wesprzeć osoby które wiedzą mniej.

Liczą się chęci i odpowiednie nastawienie. Z pewnością znajdzie się coś zarówno dla początkujących jak i dla "starych wyjadaczy" :)
