### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by afronski** [nodeschool/silesia#3]
- [x] Create official logo for _Silesia_ chapter.
  - Guidelines: https://github.com/nodeschool/nodeschool.github.io/tree/master/images/make-a-sticker
- [x] Publish it in `hexdeck.html` in main site.

**Comment by afronski** [comment]
Finished (PR is in progress)! :tada:

**Comment by martinheidegger** [comment]
I know I am being unnecessary strict but the guidelines say that you should pick 3 characters and arrange them at the guidelines :stuck_out_tongue:

**Comment by afronski** [comment]
@martinheidegger It should be better now :wink:. However I cannot see any guidelines about amount of characters and arranging them with prepared guides.

**Comment by martinheidegger** [comment]
:+1:  I still like it better :smile:

**Comment by afronski** [comment]
FTR: https://github.com/nodeschool/nodeschool.github.io/pull/193
