### ISSUE TITLE
Przyszłe Spotkania - Tematy

### ISSUE THREAD

**Issue by afronski** [nodeschool/silesia#7]
Temat do zgłaszania nowych pomysłów, na przyszłe spotkania - zarówno konkretnych warsztatów, jak i prezentacji - może ktoś chciałby poprawdzić nowy _workshopper_, którego do tej pory nie było? :wink:

**Comment by mejt** [comment]
Wczoraj jedna osoba miała prowadzić warsztaty z express.js - nie wiem czy ktoś z nich wczoraj skorzystał (ja leciałem od podstaw), ale chciałem się dowiedzieć czy te warsztaty odbywają się na tej samej zasadzie czy będzie to jakaś inna forma zadań? Dodatkowo chciałbym zapytać czy w przyszłości będzie coś związane z socket.io

**Comment by afronski** [comment]
Tak tematem _express.js_ opiekował się @bandraszyk ale nie wiem czy ktoś pracował z tym warsztatem, _workshopper_ związany z tym tematem nazywa się `expressworks` (https://github.com/azat-co/expressworks). 

Zasada jest podobna - jest lista zadań do wykonania w ramach warsztatu, ale bardzo podoba mi się propozycja @frakti dot. krótkiego wprowadzenia do tematu. Co myślisz o takim rozwiązaniu? Miałoby to sens aby na następnym spotkaniu, jeśli ktoś chciałby poznać _express.js_ bardzo krótko wprowadzić temat, pokazać małe kawałeczki kodu w mniejszym gronie a następnie pobawić się warsztatami wraz z opiekunem?

Zaciekawiłeś mnie drugim pytaniem - i odpowiedź jest prosta a jednocześnie zaskakująca - nie ma jeszcze żadnego warsztatu związanego z Web Socketami (a więc socket.io również). Szczegóły [tutaj](https://github.com/nodeschool/discussions/issues/735) i [tu](https://github.com/nodeschool/workshoppers/issues/28).

Wygląda na to, że mamy pole do popisu - @frakti @tpindel @bandraszyk @JokingHero @pawelrychlik @awilczek co myślicie o tym?

**Comment by tpindel** [comment]
@afronski myślę, że to dobry pomysł. Napiszmy nasz pierwszy _workshopper_, który będzie pokrywał socket.io.

**Comment by mejt** [comment]
@afronski wydaje mi się, że to bardzo dobry pomysł aby przyjąć trochę teorii i podstaw zanim podejdzie się do ćwiczeń :)

**Comment by afronski** [comment]
Zamykamy - spróbujemy podejść do tematu teorii inaczej na spotkaniu marcowym.
Dzięki za feedback! :wink:
