### ISSUE TITLE
stream-adventure interesujące materiały

### ISSUE THREAD

**Issue by tpindel** [nodeschool/silesia#8]
@frakti @kubavanzen Zgodnie z obietnicą wrzucam link to posta na blogu _howtonode_, który pokazuje ciekawy przykład użycia stream -ów - http://howtonode.org/coding-challenges-with-streams . Dajcie znać co o nim myślicie.

**Comment by afronski** [comment]
Przeniosłem to [tutaj](https://github.com/nodeschool/silesia/blob/master/knowledge-base/stream-adventure/MATERIALS.md).

Jeśli macie jakieś wartościowe materiały - zachęcam do przygotowania PR i rozszerzania naszej struktury!
